---
title: "cleanup.rmd"
output: html_document
---

```{r}

library(tidyverse)
library(dplyr)

d = read.csv("../data/cost-of-living.csv")
d2 <- d

d2 <- data.frame(t(d[-1]))
colnames(d2) <- d[, 1]

d3 <- d2
d3 <- cbind(rownames(d3), d3)
rownames(d3) <- NULL
colnames(d3) <- prepend(colnames(d2), "City", before = 1)
```
```{r}
d4 <- d3
d5 <- d4[, 1]
d4$City <- c("Saint Petersburg", "Istanbul", "Izmir", "Helsinki", "Chisinau", "Milan", "Cairo", "Banja Luka", "Baku", "Guadalajara", "Kathmandu", "Hanoi", "Ho Chi Minh City", "Mexico City", "Rome", "Monterrey", "Yekaterinburg", "Sarajevo", "Kharkiv", "Kiev", "Calgary", "Tunis", "Edmonton", "Amsterdam", "Belgrade", "Odessa", "Paris", "Eindhoven", "Plovdiv", "Thessaloniki", "Ottawa", "Sofia", "Rotterdam", "Varna", "Novi Sad", "Utrecht", "Berlin", "Beirut", "Austin, TX", "Singapore", "Toronto", "Auckland", "Podgorica", "Vancouver", "Tokyo", "Victoria", "Winnipeg", "Boston, MA", "Chicago, IL", "Almaty", "Oslo", "Frankfurt", "Bratislava", "Dallas, TX", "Zagreb", "Hamburg", "Krakow", "Riga", "Gdansk", "Santiago", "Nairobi", "Abu Dhabi", "Houston, TX", "Tbilisi", "Dubai", "Bogota", "Brno", "Munich", "Poznan", "Las Vegas, NV", "London", "Los Angeles, CA", "Panama City", "Seoul", "Warsaw", "Prague", "Wroclaw", "Kuala Lumpur", "New York, NY", "Copenhagen", "Ljubljana", "Chandigarh", "Colombo", "Noida", "Kaunas", "Athens", "Phoenix, AZ", "Hong Kong", "Portland, OR", "Lisbon", "Beijing", "Cape Town", "Tirana", "Porto", "Durban", "Budapest", "Vilnius", "Johannesburg", "Barcelona", "San Diego, CA", "San Francisco, CA", "Lima", "Seattle, WA", "Brasov", "Bucharest", "Tashkent", "Ahmedabad", "Cluj Napoca", "Madrid", "Tallinn", "Bangalore", "Iasi", "Chennai", "Doha", "Delhi", "Gurgaon", "Valencia", "Vienna", "Hyderabad", "Montevideo", "Tel Aviv", "Timisoara", "Taipei", "Kolkata", "Skopje", "Shanghai", "Bangkok", "Mumbai", "Reykjavik", "Amman", "Pune", "Stockholm", "Buenos Aires", "Minsk", "San Jose", "Casablanca", "Lodz", "Montreal", "Sao Paulo", "Gothenburg", "Dublin", "Moscow", "Santo Domingo", "Adelaide", "Zurich", "Yerevan", "Manila", "Brisbane", "Jakarta", "Ankara", "Lviv", "Novosibirsk", "Bursa", "Brussels", "Jerusalem", "Melbourne", "Perth", "Sydney", "Alexandria", "Quito")

d4$Country <- c("Russia", "Turkey", "Turkey", "Finland", "Moldova", "Italy", "Egypt", "Bosnia and Herzegovina", "Azerbaijan", "Mexico", "Nepal", "Vietnam", "Vietnam", "Mexico", "Italy", "Mexico", "Russia", "Bosnia and Herzegovina", "Ukraine", "Ukraine", "Canada", "Tunisia", "Canada", "Netherlands", "Serbia", "Ukraine", "France", "Netherlands", "Bulgaria", "Greece", "Canada", "Bulgaria", "Netherlands", "Bulgaria", "Serbia", "Netherlands", "Germany", "Lebanon", "USA", "Singapore", "Canada", "New Zealand", "Montenegro", "Canada", "Japan", "Canada", "Canada", "USA", "USA", "Kazakhstan", "Norway", "Germany", "Slovakia", "USA", "Croatia", "Germany", "Poland", "Latvia", "Poland", "Chile", "Kenya", "United Arab Emirates", "USA", "Georgia", "United Arab Emirates", "Colombia", "Czech Republic", "Germany", "Poland", "USA", "UK", "USA", "Panama", "South Korea", "Poland", "Czech Republic", "Poland", "Malaysia", "USA", "Denmark", "Slovenia", "India", "Sri Lanka", "India", "Lithuania", "Greece", "USA", "Hong Kong", "USA", "Portugal", "China", "South Africa", "Albania", "Portugal", "South Africa", "Hungary", "Lithuania", "South Africa", "Spain", "USA", "USA", "Peru", "USA", "Romania", "Romania", "Uzbekistan", "India", "Romania", "Spain", "Estonia", "India", "Romania", "India", "Qatar", "India", "India", "Spain", "Austria", "India", "Uruguay", "Israel", "Romania", "Taiwan", "India", "Macedonia", "China", "Thailand", "India", "Iceland", "Jordan", "India", "Sweden", "Argentina", "Belarus", "Costa Rica", "Morocco", "Poland", "Canada", "Brazil", "Sweden", "Ireland", "Russia", "Dominican Republic", "Australia", "Switzerland", "Armenia", "Philippines", "Australia", "Indonesia", "Turkey", "Ukraine", "Russia", "Turkey", "Belgium", "Israel", "Australia", "Australia", "Australia", "Egypt", "Ecuador")

d4$Latitude <- c(59.93428, 41.00824, 38.42373, 60.16986, 47.01045, 45.45863, 30.04442, 44.77218, 40.40926, 20.65970, 27.71725, 21.00312, 10.82310, 19.24647, 41.90270, 25.68661, 56.83893, 43.85626, 49.99350, 50.45010, 51.04473, 36.80649, 53.54612, 52.36670, 44.78657, 46.48253, 48.85661, 51.44164, 42.13541, 40.64006, 45.42153, 42.69771, 51.92442, 43.21405, 45.26714, 52.09074, 52.52001, 33.89379, 30.26715, 1.35208, 43.65323, -36.84846, 42.43042, 49.28273, 35.68040, 48.42842, 49.89514, 42.36008, 41.87811, 43.22201, 59.91387, 50.11092, 48.14860, 32.77666, 45.81501, 53.55108, 50.06465, 56.94965, 54.35203, -33.44889, -1.29207, 24.45388, 29.76043, 41.71514, 25.20485, 4.71099, 49.19506, 48.13513, 52.40637, 36.16994, 51.50735, 34.05223, 8.98238, 37.56654, 52.22968, 50.07554, 51.10789, 3.15695, 40.71278, 55.67610, 46.05695, 30.73331, 6.92708, 28.53552, 54.89852, 37.98381, 33.44838, 22.28247, 45.50511, 38.72225, 39.90420, -33.92487, 41.32755, 41.15794, -29.85868, 47.49791, 54.68716, -26.20410, 41.38506, 32.71574, 37.77493, -12.04637, 47.60621, 45.65798, 44.42677, 41.29950, 23.02251, 46.77121, 40.41678, 59.43696, 12.97160, 47.15845, 13.08268, 25.28545, 28.68627, 28.45950, 39.46991, 48.20817, 17.38504, -34.81816, 32.08530, 45.74887, 25.03297, 22.57265, 42.00503, 31.23042, 13.75633, 19.07598, 64.14658, 31.95395, 18.52043, 59.32932, -34.60368, 53.90060, 9.91297, 33.57311, 51.75925, 45.50169, -23.54318, 57.70887, 53.34981, 55.75583, 18.48606, -34.92850, 47.37689, 40.18720, 14.60905, -27.46977, -6.20876, 39.93336, 49.83968, 55.00835, 40.18853, 50.85034, 31.76832, -37.81363, -31.95053, -33.86882, 31.20009, -0.18065)

d4$Longitude <- c(30.33510, 28.97836, 27.14283, 24.93838, 28.86381, 9.18187, 31.23571, 17.19100, 49.86709, -103.34961, 85.32396, 105.82014, 106.62966, -99.10135, 12.49624, -100.31611, 60.60570, 18.41308, 36.23038, 30.52340, -114.07188, 10.18153, -113.49382, 4.89454, 20.44892, 30.72331, 2.35222, 5.46972, 24.74529, 22.94442, -75.69719, 23.32187, 4.47773, 27.91473, 19.83355, 5.12142, 13.40495, 35.50178, -97.74306, 103.81984, -79.38318, 174.76333, 19.25936, -123.12074, 139.76902, -123.36564, -97.13837, -71.05888, -87.62980, 76.85125, 10.75225, 8.68213, 17.10775, -96.79699, 15.98192, 9.99368, 19.94498, 24.10519, 18.64664, -70.66927, 36.82195, 54.37734, -95.36980, 44.82710, 55.27078, -74.07209, 16.60684, 11.58198, 16.92517, -115.13983, -0.12776, -118.24368, -79.51987, 126.97797, 21.01223, 14.43780, 17.03854, 101.71230, -74.00597, 12.56834, 14.50575, 76.77942, 79.86124, 77.39103, 23.90360, 23.72754, -112.07404, 114.16157, -122.67503, -9.13934, 116.40740, 18.42406, 19.81870, -8.62911, 31.02184, 19.04024, 25.27965, 28.04731, 2.17340, -117.16108, -122.41942, -77.04275, -122.33207, 25.60120, 26.10254, 69.24007, 72.57136, 23.62364, -3.70379, 24.75357, 77.59456, 27.60144, 80.27072, 51.53104, 77.22178, 77.02664, -0.37629, 16.37382, 78.48667, -56.21383, 34.78177, 21.20868, 121.56542, 88.36390, 21.44077, 121.47370, 100.50177, 72.87766, -21.94264, 35.91064, 73.85674, 18.06858, -58.38156, 27.55897, -84.07683, -7.58984, 19.45598, -73.56726, -46.62918, 11.97456, -6.26031, 37.61730, -69.93121, 138.60075, 8.54169, 44.51521, 121.02226, 153.02512, 106.84560, 32.85974, 24.02972, 82.93573, 29.06096, 4.35171, 35.21371, 144.96306, 115.86046, 151.20930, 29.91874, -78.46784)
```
```{r}
d6 <- d4[, c(1, 57, 58, 59, 2:56)]
write.csv(d6, "../data/cleaned_cost_of_living.csv")
```
